### ISSUE TITLE
Regarding semu-c64 timelapse capture

### ISSUE THREAD

**Issue by hpingel** [onnokort/cc3000-simple#1]
Hi Onno Kortmann,

sorry to hijack this project but this seems to be the only way to contact you that I can find.

I wanted to let you know that I am booting your Linux kernel in a Youtube livestream that is now running for 8 hours already:
https://www.youtube.com/watch?v=g-36d07DfgI

Great project!
Cheers
Henning

**Comment by onnokort** [comment]
Hi, yeah that is great, thank you! :-)
I found your YT stream myself already. I have opened the issue page on github now! My eMail is in the commit messages.
Expect it to stay at the log line it is now for the night or so. The time markers should scale
linearly, so if you scroll back in your own life stream and look at the GIF I posted (which IIRC I made with
the same or a very close kernel configuration), you can kind of estimate when the "next thing" happens.
I have updated the kernel to use cramfs (~1/3rd boot speed improvement) and hope to to post some code updates later.
